app:
  description: account service is a Spring Boot applications
  name: accounts-movements-service
  environment: ${ENVIRONMENT:dev}
  ms:
    customer-service:
      url: ${CUSTOMER_SERVICE_URL:http://localhost:8080}
spring:
  main:
    allow-circular-references: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: ${GLOBAL_KAFKA_HOST_PLAIN:localhost:9092}
    consumer:
      group-id: ${MS_NAME:account_service}
      bootstrap-servers: ${GLOBAL_KAFKA_HOST_PLAIN:localhost:9092}
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:accounts;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      idle-timeout: 20000
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          time_zone: ${TIME_ZONE:UTC}
        format_sql: true

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:}
  error:
    include-stacktrace: always
    include-message: always
resilience4j:
  retry:
    instances:
      customerClientRetry:
        maxAttempts: 5
        waitDuration: 5000ms
        retryExceptions:
          - java.io.IOException
        ignoreExceptions:
          - java.net.SocketTimeoutException

  circuitbreaker:
    instances:
      customerClientCircuit:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000ms
        failureRateThreshold: 50
        eventConsumerBufferSize: 10